// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rcteeqvosthccuepebmr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjdGVlcXZvc3RoY2N1ZXBlYm1yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk3MDY1MjUsImV4cCI6MjA4NTI4MjUyNX0.R8mHdq2m_sku0LnLSYKPjmbjIUmEXZoo4CDukpGm1d0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});